#!/usr/bin/env bash

if [[ -n $FISH_EXISTS ]]; then
  # shellcheck disable=SC2068
  gclone newrepo --print-output-dir fish $@
else
  # shellcheck disable=SC2068
  gclone newrepo --print-output-dir sh $@
fi
